### ISSUE TITLE
Ljspeech alignment file

### ISSUE THREAD

**Issue by Jimvc** [reppy4620/x-vits#3]
Hello. Thank you for your work.
When I try to use the Ljspeech data set, follow
'exp/ljspeech/01_data/01_preprocess/dummy.sh'.
'# alignment file is extracted by montreal forced aligner
# https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner
alignment_dir=D:/downlod/xvits_en/alignment'

I use pycharm to open the 'Montreal-Forced-Aligner-main' downloaded from github.
How do I generate an alignment file?

**Comment by reppy4620** [comment]
Hi Jimvc,

This repository does not contain instructions about alignment generation, so please follow the instructions below
1. install Montreal Forced Aligner : https://montreal-forced-aligner.readthedocs.io/en/latest/getting_started.html
2. Run the MFA : https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/index.html#first-steps

Although the above website contains all features of MFA, it can be difficult to understand how to use it if you are not familiar with it.
This is a brief introduction on how to use MFA.

# Requirement
1. Anaconda or Miniconda 
2. LJSpeech corpus

# Usage
## 1. Create environment by using conda,  install MFA and MFA setup

1. Create environment by using conda
e.g.
```
conda create -n alignment python=3.10
```

2. Install MFA
```
conda activate alignment
conda config --add channels conda-forge
conda install montreal-forced-aligner
```

3. Setup MFA for english corpus
```
mfa model download acoustic english_us_arpa
mfa model download dictionary english_us_arpa
```

# 2. Make directory which contains all wav and transcription files.
For example, run the following script after changing the `wav_dir` and `metadata_file` variables to fit your environment.
If you run the script, an output directory containing all required files will be created as `wav_transcript`.
```sh
#!/bin/bash

out_dir=./wav_transcript
mkdir -p $out_dir

wav_dir=/path/to/LJSpeech/wav
metadata_file=/path/to/LJSpeech/metadata.csv

# Create transcript files
while IFS='|' read -r bname tmp transcript; do
    echo $bname
    echo $transcript > $out_dir/${bname}.txt
done < $metadata_file

# Create wav file as symbolic link
cd $out_dir
for fpath in $wav_dir/*.wav; do
    fname=$(basename $fpath)
    echo $fname
    ln -s $fpath $fname
done
```

# 3. Run MFA

For example, run the following script after changing wav_transcript_dir variable to fit your environment.
If you run this script, an output directory containing alignment will be created as  `alignment`.
```sh
#!/bin/bash

out_dir=./alignment
mkdir -p $out_dir

wav_transcript_dir=/path/to/wav_transcript

# use 4 cores ( -j 4 )
mfa align --clean --overwrite --single_speaker -j 4 ${wav_transcript_dir} english_us_arpa english_us_arpa ${out_dir}
```

The directory named `alignment` is what you want.

**Comment by Jimvc** [comment]
Thank you reppy4620, it helps a lot.
