### ISSUE TITLE
loss=nan

### ISSUE THREAD

**Issue by Jimvc** [reppy4620/x-vits#5]
Hello, reppy4620.
When I used LJspeech corpus, I modified "config/text_encoder/num_vocab:160". The program can run. 
But when epoch=170, I have a problem：”b=3.985, disc=nan, gen=nan, fm=nan,“.
I don't have this problem with "jsut".
Have you ever encountered this problem? I don't know if it's the data set or if I changed ”num_vocab“ from 100 to 160
Thank you for your reply。

**Comment by reppy4620** [comment]
Hi Jimvc, sorry for late reply.

This is an issue I have experience with as well.
It's likely that luck also plays a part in this issue. 
Stability is a challenging aspect, and it may be due to training with fp16.

**Comment by Jimvc** [comment]
Thank you,reppy4620.
I changed the learning rate from 2e-4 to 1e-4. Let's see how it goes.
